name: Issue Commenter

on:
  issues:
    types: [opened]

permissions:
  issues: write

jobs:
  comment:
    runs-on: ubuntu-latest

    steps:
    - name: Comment on new issue
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const { owner, repo } = context.repo;
          const issue_number = context.issue.number;

          await github.rest.issues.createComment({
            owner,
            repo,
            issue_number,
            body: "Let's start work"
          });
