name: Issue Labeler

on:
  issues:
    types: [opened, edited]

permissions:
  issues: write

jobs:
  comment:
    runs-on: ubuntu-latest

    steps:
    - name: Label the issue based on its body content
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const { owner, repo } = context.repo;
          const issue_number = context.issue.number;
          const issue_body = context.payload.issue.body;

          let labels = [];

          if (!issue_body || issue_body.trim() === "") {
            labels = ["action required"];
          } else if (issue_body.toLowerCase().includes("version")) {
            labels = ["documentation"];
          } else {
            labels = ["bug"];
          }

          await github.rest.issues.addLabels({
            owner,
            repo,
            issue_number,
            labels: labels
          });

    - name: Comment on the issue
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const { owner, repo } = context.repo;
          const issue_number = context.issue.number;

          await github.rest.issues.createComment({
            owner,
            repo,
            issue_number,
            body: "Thanks for creating or editing this issue. A new label added to the issue."
          });
